### ISSUE TITLE
Bugs and Credits

### ISSUE THREAD

**Issue by thehappydinoa** [TheGabrielHoward/FlipToShhhEnabler#1]
Hey man,

Just a few things: 

- Make sure to remove the `rm /data/resource-cache/overlays.list` in the `uninstall.sh`
- You also have an extra `fi` on line 12 in `install.sh`
- Make sure to check for `com.google.android.apps.wellbeing` on install and abort if not found
- Please at least credit me or Pix3lify for this code.

Thanks,
thehappydinoa

**Comment by TheGabrielHoward** [comment]
@thehappydinoa I'll keep it in mind
